kind: Service
apiVersion: v1
metadata:
  name: xpaucof-hospital-webapi
spec:
  selector:
    pod: xpaucof-hospital-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: webapi-port
