/*
 * Hospital Ward Api
 *
 * Hospital Ward management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xpaucof@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hospital_wl

import (
	"github.com/gin-gonic/gin"
)

type BedsAPI interface {

	// CreateBed Post /api/ward/:wardId/beds
	// Creates a new bed in a ward
	CreateBed(c *gin.Context)

	// DeleteBed Delete /api/ward/:wardId/beds/:bedId
	// Deletes a specific bed
	DeleteBed(c *gin.Context)

	// GetBed Get /api/ward/:wardId/beds/:bedId
	// Provides details about a bed
	GetBed(c *gin.Context)

	// GetBeds Get /api/ward/:wardId/beds
	// Provides the list of beds for a ward
	GetBeds(c *gin.Context)

	// UpdateBed Put /api/ward/:wardId/beds/:bedId
	// Updates a specific bed
	UpdateBed(c *gin.Context)
}
