/*
 * Hospital Ward Api
 *
 * Hospital Ward management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xpaucof@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hospital_wl

import (
	"github.com/gin-gonic/gin"
)

type VisitsAPI interface {

	// CreateVisit Post /api/ward/:wardId/visits
	// Creates a new visit for a ward
	CreateVisit(c *gin.Context)

	// DeleteVisit Delete /api/ward/:wardId/visits/:visitId
	// Deletes a specific visit
	DeleteVisit(c *gin.Context)

	// GetVisit Get /api/ward/:wardId/visits/:visitId
	// Provides details about a visit
	GetVisit(c *gin.Context)

	// GetVisits Get /api/ward/:wardId/visits
	// Provides the list of visits for a ward
	GetVisits(c *gin.Context)

	// UpdateVisit Put /api/ward/:wardId/visits/:visitId
	// Updates a specific visit
	UpdateVisit(c *gin.Context)
}
