/*
 * Hospital Ward Api
 *
 * Hospital Ward management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xpaucof@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hospital_wl

type Bed struct {

	// Unique id of the bed
	Id string `json:"id"`

	// Bed/room number
	Number string `json:"number"`

	// Current status of the bed
	Status string `json:"status"`

	// Department where the bed belongs
	Department string `json:"department"`

	// ID of the patient currently in the bed (if occupied)
	PatientId string `json:"patientId,omitempty"`
}
