/*
 * Hospital Ward Api
 *
 * Hospital Ward management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xpaucof@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hospital_wl

type Visit struct {

	// Unique id of the visit
	Id string `json:"id"`

	// Unique identifier of the patient
	PatientId string `json:"patientId"`

	// Unique identifier of the bed where visit took place
	BedId string `json:"bedId"`

	// Date of the visit
	Date string `json:"date"`

	// Time of the visit (HH:MM)
	Time string `json:"time"`

	// List of attending doctors
	Doctors []string `json:"doctors,omitempty"`

	// Clinical notes from the visit
	ClinicalNotes string `json:"clinicalNotes,omitempty"`
}
