/*
 * Hospital Ward Api
 *
 * Hospital Ward management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xpaucof@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hospital_wl

type Ward struct {

	// Unique identifier of the ward
	Id string `json:"id"`

	// Human readable name of the ward
	Name string `json:"name"`

	Visits []Visit `json:"visits,omitempty"`

	Beds []Bed `json:"beds,omitempty"`
}
